version: 2
jobs:
  test:
    working_directory: ~/app
    docker:
      - image: boardman/angular-twit-circleci-base:0.0.1
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: Run tests
          command: yarn test --single-run  --progress false
      - run:
          name: Linting
          command: yarn lint
          prefix: lint
      # - run:
      #     name: Push application Docker image
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]
      #       then
      #         login="$(aws ecr get-login)"
      #         ${login/"-e none"/""}
      #         docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
      #         docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
      #       fi
  build_image:
    working_directory: ~/app
    docker:
      - image: boardman/angular-twit-circleci-base:0.0.1
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - ~/caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i ~/caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --rm=false --cache-from=app -t eu.gcr.io/${GOOGLE_PROJECT_ID}/angular-twit:$CIRCLE_SHA1 .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p ~/caches
            docker save -o ~/caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/caches/app.tar
  push_and_deploy:
    docker:
      - image: boardman/angular-twit-circleci-base:0.0.1
    steps:
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - ~/caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i ~/caches/app.tar | true
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Configure gcloud
          command: |
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
            gcloud auth configure-docker
      - run:
          name: Push image to google container registry
          command: docker push eu.gcr.io/${GOOGLE_PROJECT_ID}/angular-twit:$CIRCLE_SHA1
      - run:
          name: Patch deployment
          command: echo NOT IMPLEMENTED - patch deployment to be added


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - build_image:
          requires:
            - test
          filters:
            branches:
              only: master
      - push_and_deploy:
          requires:
            - build_image
          filters:
            branches:
              only: master

