version: 2
jobs:
  build:
    working_directory: ~/angular-twit
    docker:
      - image: circleci/node:8-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: angular-build
          command: yarn build --prod --aot --progress false
      - run:
          name: angular-test
          command: yarn test --single-run  --progress false
      - run:
          name: angular-lint
          command: yarn lint
          prefix: lint
  deploy:
    docker:
      - image: my-image
    working_directory: /tmp/angular-twit
    steps:
      - run:
          name: Deploy Master to GKE
          command: ./deploy.sh


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
